# Generated by Django 4.2.4 on 2023-08-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='banos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='habitaciones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_principal',
            field=models.ImageField(default='propiedad_default.jpg', upload_to='propiedades/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='metros_cuadrados',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_propiedad',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], default='venta', max_length=10),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ubicacion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
