# Generated by Django 4.1.6 on 2023-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_rename_fecha_publicacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='ubicacion',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='provincia',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('temporada', 'Temporada')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_propiedad',
            field=models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('deposito', 'Deposito'), ('edificio', 'Edificio'), ('quinta', 'Quinta Vacacional')], default='', max_length=20),
        ),
    ]
