# Generated by Django 4.1.6 on 2023-09-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_alter_publicacion_imagen_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='banos',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ambientes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
