# Generated by Django 4.1.6 on 2023-09-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_alter_publicacion_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('temporada', 'Temporada')], default='alquiler', max_length=10),
        ),
    ]
