# Generated by Django 4.1.6 on 2023-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_remove_publicacion_banos_publicacion_ambientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='sitio.publicacion'),
        ),
    ]
