# Generated by Django 4.1.6 on 2023-09-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_publicacion_tipo_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='ambientes',
        ),
        migrations.AddField(
            model_name='profile',
            name='favoritas',
            field=models.ManyToManyField(blank=True, to='sitio.publicacion'),
        ),
    ]
