# Generated by Django 4.1.6 on 2023-09-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_publicacion_tipo_operacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='ambientes',
            new_name='ambientes',
        ),
    ]
