# Generated by Django 4.1.6 on 2023-09-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_rename_banos_publicacion_ambientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoritas',
            field=models.ManyToManyField(blank=True, to='sitio.publicacion'),
        ),
    ]
