# Generated by Django 4.1.6 on 2023-09-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_profile_favoritas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='ambientes',
        ),
    ]
