# Generated by Django 4.1.6 on 2023-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_remove_publicacion_ambientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ambientes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
