# Generated by Django 4.1.6 on 2023-09-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_publicacion_expensas'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='banios',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
